version: "3.2"
services:
  web:
    build: .
    volumes:
      - ./php/src:/var/www/html/
    ports:
      - "80:80"

  db:
    image: mariadb:10.7.4
    volumes:
      - ./db:/var/lib/mysql:Z
    environment:
      - MARIADB_ROOT_PASSWORD=azertyahah
      - PMA_HOST=db

  pma: 
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - MYSQL_ROOT_PASSWORD=azertyahah
      - PMA_USER=root
      - PMA_PASSWORD=azertyahah      